const headphones = [{
    id: 1,
    tag: "hero-product",
    tagline: "Keep the noise out, or in. You choose.",
    heroImage: "../Assets/images/products/jbl660nc-1.png",
    images: [
        "../Assets/images/products/jbl660nc-1.png",
        "../Assets/images/products/jbl660nc-2.png",
        "../Assets/images/products/jbl660nc-3.png",
        "../Assets/images/products/jbl660nc-4.png",
    ],
    brand: "JBL",
    title: "JBL Live 660NC",
    info: "Wireless Over-Ear NC Headphones",
    category: "Headphones",
    type: "Over Ear",
    connectivity: "Wireless",
    finalPrice: 9999,
    originalPrice: 14999,
    quantity: 1,
    ratings: 1234,
    rateCount: 5,
    path: "/product-details/",
},
{
    id: 2,
    tag: "featured-product",
    heroImage: "../Assets/images/products/boat518-1.png",

    images: [
        "../Assets/images/products/boat518-1.png",
        "../Assets/images/products/boat518-2.png",
        "../Assets/images/products/boat518-3.png",
        "../Assets/images/products/boat518-4.png"
    ],
    brand: "boAt",
    title: "boAt Rockerz 518",
    info: "On-Ear Wireless Headphones",
    category: "Headphones",
    type: "On Ear",
    connectivity: "Wireless",
    finalPrice: 1299,
    originalPrice: 3990,
    quantity: 1,
    ratings: 1321,
    rateCount: 5,
    path: "/product-details/",
},
{
    id: 3,
    heroImage: "../Assets/images/products/boat410-1.png",

    images: [
        "../Assets/images/products/boat410-1.png",
        "../Assets/images/products/boat410-2.png",
        "../Assets/images/products/boat410-3.png",
        "../Assets/images/products/boat410-4.png",
    ],
    brand: "boAt",
    title: "boAt Rockerz 410",
    info: "Bluetooth & Wired On-Ear Headphones",
    category: "Headphones",
    type: "On Ear",
    connectivity: "Bluetooth & Wired",
    finalPrice: 1599,
    originalPrice: 2990,
    quantity: 1,
    ratings: 1563,
    rateCount: 5,
    path: "/product-details/",
},
{
    id: 4,
    tag: "hero-product",
    
    heroImage: "../Assets/images/products/sonyxb910n-1.png",
    images: [
        "../Assets/images/products/sonyxb910n-1.png",
        "../Assets/images/products/sonyxb910n-2.png",
        "../Assets/images/products/sonyxb910n-3.png",
        "../Assets/images/products/sonyxb910n-4.png",
    ],
    brand: "Sony",
    title: "Sony WH-XB910N",
    info: "Wireless Over-Ear Headphones",
    category: "Headphones",
    type: "Over Ear",
    connectivity: "Wireless",
    finalPrice: 13489,
    originalPrice: 19990,
    quantity: 1,
    ratings: 679,
    rateCount: 4,
    path: "/product-details/",
},
{
    id: 5,
    tag: "featured-product",
    heroImage: "../Assets/images/products/jbl760nc-1.png",

    images: [
        "../Assets/images/products/jbl760nc-1.png",
        "../Assets/images/products/jbl760nc-2.png",
        "../Assets/images/products/jbl760nc-3.png",
        "../Assets/images/products/jbl760nc-4.png",
    ],
    brand: "JBL",
    title: "JBL Tune 760NC",
    info: "Wireless Over-Ear NC Headphones",
    category: "Headphones",
    type: "Over Ear",
    connectivity: "Wireless",
    finalPrice: 5999,
    originalPrice: 7999,
    quantity: 1,
    ratings: 755,
    rateCount: 4,
    path: "/product-details/",
},
{
    id: 6,
    heroImage: "../Assets/images/products/sonych710n-1.png",

    images: [
        "../Assets/images/products/sonych710n-1.png",
        "../Assets/images/products/sonych710n-2.png",
        "../Assets/images/products/sonych710n-3.png",
        "../Assets/images/products/sonych710n-4.png",
    ],
    brand: "Sony",
    title: "Sony WH-CH710N",
    info: "Wireless Over-Ear NC Headphones",
    category: "Headphones",
    type: "Over Ear",
    connectivity: "Wireless",
    finalPrice: 8520,
    originalPrice: 14990,
    quantity: 1,
    ratings: 853,
    rateCount: 4,
    path: "/product-details/",
},
{
    id: 7,
    heroImage: "../Assets/images/products/jbl500bt-1.png",

    images: [
        "../Assets/images/products/jbl500bt-1.png",
        "../Assets/images/products/jbl500bt-2.png",
        "../Assets/images/products/jbl500bt-3.png",
        "../Assets/images/products/jbl500bt-4.png",
    ],
    brand: "JBL",
    title: "JBL Tune 500BT",
    info: "On-Ear Wireless Headphones",
    category: "Headphones",
    type: "On Ear",
    connectivity: "Wireless",
    finalPrice: 3282,
    originalPrice: 3999,
    quantity: 1,
    ratings: 364,
    rateCount: 4,
    path: "/product-details/",
},
]

export default headphones;